### ISSUE TITLE
Rename FAGDec

### ISSUE THREAD

**Issue by Formedras** [CelesteBlue-dev/PSVita-RE-tools#3]
There is little legitimate reason to keep the first three letters in the name, in that order, and having it without real reason strongly implies hatred of non-straight people. The name needs to be changed.

**Comment by dots-tb** [comment]
You imply a strong hatred of AMERICANS and FRENCH. Commie.

**Comment by nightyasen** [comment]
>strongly implies hatred of non-straight people
You're looking for issues where there are none. There is no hatred, implicit nor explicit. You would have complained had the word been Leafages as well, eh?

**Comment by SilicaAndPina** [comment]
The only thing that's offensive is that gay people think there special snowflakes who no one is ever allowed to criticize. And never learnt that not everything is about them.

**Comment by nightyasen** [comment]
>gay people think there special snowflakes

gay people don't care kek.
it's people getting offended on gay people's behalf, a la OP

**Comment by Formedras** [comment]
I didn't object to any single word. No hatred of Americans or French, or French-Americans. And although I consider PURE (not Russian-style) communism to be ideal, no human-run communism can work for more than a couple of years, at best.

I'm bisexual. I was merely concerned about potential offence before. I AM offended now.

**Comment by SilicaAndPina** [comment]
>I'm bisexual

Wow all-knowing yasen was right!!!
It *IS* never gays who acturally complain

**Comment by nightyasen** [comment]
Ignoring Silica’s childish remarks and Dots calling everyone a communist, are you still offended?

Because “Fag” refers to male homosexuals. I can understand you getting concerned about others getting offended, but this is silly to file an issue about it, in my opinion, as it is no longer just a concern but taking action against the possibility of offense. 
If it bothers you that much, you’re free to redistribute it with renames or build your own app from the start. It’s open source.

**Comment by amadeusnorn** [comment]
or mayber FAG is a acronym for something else and its not intended to be homophobic?

**Comment by ness151** [comment]
Honestly, as someone stated before, fork the project, rename it, and make it better.  That could be one way to get the change you want.

**Comment by MystiK791** [comment]
@Formedras I'm glad this tool is depreciated now. I felt really, really, dirty for just the 5 minutes I had this tool on my Vita, and I made sure to scrub every trace of it after I was done using it. I hate that word, I hate its origins, and yet I _had_ to use this tool for Project Lighthouse as it was the only option at the time.

 If the name meant so much, why not reorder it "American-French Games Decrypter"? Then everyone would have been happy. Not to mention AFGdec is a cooler-looking acronym IMO.

**Comment by KuromeSan** [comment]
just putting this out there; im with with @MystiK791

**Comment by MystiK791** [comment]
> just putting this out there; i'm 100% with @MystiK791, @Formedras, etc. ^ 

Thank you ^_^


> you could also go with "GAF" and then you can have double meaning of like "give-a-fuck" which is also cool.

I like this! 

> also this tool also still the easiest way to decrypt vita game executable (as far as i know?)

Sadly, yes, otherwise projects like Beacon wouldn't still use it. The people running it hate this tool's name as well, however, they still use it because it's easier to say "install this tool, press a button, and boom" (especially since they're trying to make it so even the people newest to modding in general can still use the project) than:
 "ok, now, open Vitashell, go to your patch folder, go to your game's ID, press triangle, press open decrypted. Copy the eBOOT somewhere in ux0. Copy that to your PC. Run this _other_ tool on your PC, and _then_ you'll have a decrypted eBOOT".

See what I mean?

**Comment by Formedras** [comment]
These people are not going to change the offensive name. They made it clear that they [b]LIKE[/b] attacking marginalized people and they've proven that over and over. Other skilled programmers need to create replacements and kick this kind of person out of the Vita and homebrew communities.

**Comment by SonicMastr** [comment]
Could you guys just fork it and get it over with? This has been closed for 4 years now and it's honestly not hurting anybody. Nor do you actually have to use it anymore.

It's getting sad

The creators do more than you know, and they're not simply getting kicked out over something you guys got offended over. Calm down a bit, ok? Nobody is attacking you. Just take your own personal name change and stop yelling at a cloud

**Comment by koutsie** [comment]
Just fork it and be done with it :neckbeard:

**Comment by swindlesmccoop** [comment]
The people that are offended are the people that can't write their own working software.

**Comment by wchristian** [comment]
personally as a gay person i like keeping the name as is because it means one of two things:
- either the creators are flamboyant fags like me
- or the creators are nazis unlike me

and thus one knows when interacting one should take care of warning flags and inspect their behaviors to see if which way it shakes out has bearing on oneself personally

**Comment by MystiK791** [comment]
> Nor do you actually have to use it anymore.

Yes, you do. See my comment above

> The creators do more than you know, and they're not simply getting kicked out over something you guys got offended over. Calm down a bit, ok? Nobody is attacking you. Just take your own personal name change and stop yelling at a cloud

I was just putting in my two cents, I didn't expect everybody and their mom to come and flame me for doing so.

**Comment by MystiK791** [comment]
> The people that are offended are the people that can't write their own working software.

That's a very elitist attitude to have :/

**Comment by KuromeSan** [comment]
> That's a very elitist attitude to have :/

ironically the very sort of thing the 'cbps' team was originally meant to combat was developers being super elitist lol

**Comment by MystiK791** [comment]
> also in this case its more "can they run a .SFO editor ?"
Yes

**Comment by MystiK791** [comment]
Also, problem solved: https://github.com/MystiK791/Generic-Games-Decrypter

**Comment by KuromeSan** [comment]
> Also, problem solved: https://github.com/MystiK791/Generic-Games-Decrypter
looking at this commit log, there aren't too many places where it actually says the slur, if the full name "French American Games Decryptor" was always used and never abbreviated it'd possibly be fine?

**Comment by MystiK791** [comment]
> > Also, problem solved: https://github.com/MystiK791/Generic-Games-Decrypter
> 
> looking at this commit log, there aren't too many places where it actually says the slur, if the full name "French American Games Decryptor" was always used and never abbreviated it'd possibly be fine? 
> 

I mean, yea. That is true. However, it also had the slur displayed in fairly large letters while the app was running.


I like GGdec because the only community that still regularly uses it (LBPUnion) is primarily based on Discord. Discord uses the domain .gg. Also, I'm hoping to add some stuff like actual livearea assets, and maybe automation of decrypting files for certain projects (such as Beacon).

**Comment by Formedras** [comment]
> I was just putting in my two cents, I didn't expect everybody and their mom to come and flame me for doing so.

Although I'm certainly with you in the anti-bigot camp, I kinda feel like you should have seen the attacks coming a mile away, just from the messages that came before. It's all kinds of the same bigoted rationalization that you get from people who shout down Black people by screaming "All Lives Matter," or try to claim that men will dress up as women to get into women's restrooms. It's all fraudulent, they know it, but they act like it's a real argument.

Now, I'm not saying that you shouldn't have said anything. I'm glad to know that someone in the Vita community isn't a January 6 apologist. Just that you should have known that you'd be attacked. (And then posted anyway because it's the right thing to do.)

**Comment by MystiK791** [comment]
@Formedras Ok, maybe not "didn't expect" lol.

I forked the app, so after 4 years, this app now has a name that is 100% inoffensive
