### ISSUE TITLE
Improper cmake for kdumper

### ISSUE THREAD

**Issue by mathieulh** [CelesteBlue-dev/PSVita-RE-tools#8]
In the kdump project CMakeLists.txt links SceKernelThreadmgr_stub_weak, in the latest Vita SDK it's SceKernelThreadMgr_stub_weak
Compilation errors will occur if this issue is not fixed while the latest vita sdk is installed.

**Comment by CelesteBlue-dev** [comment]
Have you tried compiling it ?

**Comment by mathieulh** [comment]
Of course, it fails unless I make that change, I am using the latest vitasdk.
Apparently -lSceDriverUser_stub_weak doesn't seem to be required either.

**Comment by CelesteBlue-dev** [comment]
Kdumper source code is only for devs as it is a WiP.
 SceKernelThreadmgr_stub_weak was either a mistake or was because I was compiling with OLD official SDK stubs... (for testing on low firmwares like 3.18).
-lSceDriverUser_stub_weak is there because I was trying to call sceAppMgrLaunchApp instead of _sceAppMgrLaunchApp.
